import { Component } from '@angular/core';

@Component({
  selector: 'app-estoque',
  templateUrl: './estoque.component.html',
  styleUrls: ['./estoque.component.scss'],
})

export class EstoqueComponent {
  mockProdutos = [
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },

    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },
    {
      codigo: '#1234',
      nome: 'Guarana Lara 300ml',
      categoria: 'Refrigerante',
      quantidade: '12',
      qtdMinima: '10',
      ValorCompra: 'R$ 3.00',
      ValorVenda: 'R$ 4.00',
      Entrada: '01/01/2023',
    },

  ];
}
